id: ABE6B5339
title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The Nucleus
  of Blessings’
type: translation
pechas:
- IADE69178
- I92EE3899
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:56.327188
  last_modified_at: 2023-01-04 12:00:56.327204
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IADE69178/AAA6: '0103'
  I92EE3899/9C71: '0103'
